Repository aj-rom/BackPacksPlus, pull requests merged in 2021-04, with the labels that each got.

#11 Dupe fix
  pom.xml
  src/main/java/io/github/coachluck/backpacksplus/listeners/BackPackCloseListener.java
Labels: bug

#14 creating the translation file
  src/main/resources/lang/pt-br.yml
Labels: enhancement

#15 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#16 Add turkish translations
  src/main/resources/lang/tr.yml
Labels: enhancement

#17 Update default backpacks file
  pom.xml
  src/main/resources/backpacks.yml
Labels: enhancement
